spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/educator?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
     prefix: classpath:/templates/
     check-template-location: true
     suffix: .html
     encoding: UTF-8
     mode: HTML #LEGACYHTML5
     cache: false
  security:
    user:
      name: sunyu
      password: sunyu